### ISSUE TITLE
Problem with Mixcr parsing recently

### ISSUE THREAD

**Issue by mimisikai** [mikessh/vdjtools#70]
I face the issue when I input the Mixcr data as:
java.lang.RuntimeException: Unable to parse clonotype string 0	5191	0.003440188372017504	TGTGCAAGATGGGGTTCTACGGCCTACTACTTTGACTACTGG	GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG	IGHV1-72*00(1076.1),IGHV1-62-3*00(1040.5),IGHV1-62*00(976.6)	IGHD2-3*00(33),IGHD1-1*00(30)	IGHJ2*00(244.1)	IGHA*00(402.8)	285|295|314|0|10||50.0;285|295|314|0|10||50.0;284|294|313|0|10||50.0	25|35|51|12|21|DA29|33.0;30|36|69|16|22||30.0	19|37|68|24|42||90.0												TGTGCAAGATGGGGTTCTACGGCCTACTACTTTGACTACTGG	38								CARWGSTAYYFDYW		:::::::::0:1:10:12:-8:1:21:24:1:42::: for VDJtools input type: Unknown nucleotide: "0".

The Mixcr results are from version 2.1.1 and 2.1.2-rc0. I doubt whether the compatibility issue btw Mixcr and VDJtools.

**Comment by mimisikai** [comment]
Double check in the Mac. The same issue.

**Comment by mikessh** [comment]
The error ``for VDJtools input type`` suggests that you're trying to load the sample as is, without converting it to VDJtools format first. Have you tried to run ``vdjtools Convert -S mixcr ...`` and then use VDJtools routines on converted files?

**Comment by mimisikai** [comment]
Issue with ggplot2…. Please help me out. Thank you!

 

Install all required R packages, and Rscript --version also works.

R version is R scripting front-end version 3.4.0 (2017-04-21)

vdjtools version is VDJtools V1.1.4.

 

 

Executing com.antigenomics.vdjtools.basic.PlotFancySpectratype RMM590.txt out/3
[Wed Apr 26 20:52:06 PDT 2017 PlotFancySpectratype] Reading sample
[Wed Apr 26 20:52:06 PDT 2017 SampleStreamConnection] Loading sample RMM590
[Wed Apr 26 20:52:08 PDT 2017 ClonotypeStreamParser] Finished parsing 44026 lines. 1 header and 0 bad line(s) were skipped. Bad line statistics: NO_CDR3NT=0, NO_CDR3AA=0, NO_V=0, NO_J=0, ZERO_COUNT=0, ZERO_FREQ=0, BAD_LINE=0
[Wed Apr 26 20:52:08 PDT 2017 SampleStreamConnection] Loaded sample RMM590 with 44026 clonotypes and 1508929 cells. Memory usage: 2 of 3 GB
[Wed Apr 26 20:52:08 PDT 2017 PlotFancySpectratype] Writing output and plotting data
[RUtil] Executing Rscript fancy_spectratype.r out/3.fancyspectra.txt out/3.fancyspectra.pdf Clonotype TRUE
[ERROR] Loading required package: ggplot2

*** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
1: dyn.load(file, DLLpath = DLLpath, ...)
2: library.dynam(lib, package, package.lib)
3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
4: asNamespace(ns)
5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
6: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
7: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]), from = package)
8: loadNamespace(package, lib.loc)
9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch({ attr(package, "LibPath") <- which.lib.loc ns <- loadNamespace(package, lib.loc) env <- attachNamespace(ns, pos = pos, deps)}, error = function(e) { P <- if (!is.null(cc <- conditionCall(e))) paste(" in", deparse(cc)[1L]) else "" msg <- gettextf("package or namespace load failed for %s%s:\n %s", sQuote(package), P, conditionMessage(e)) if (logical.return) message(paste("Error:", msg), domain = NA) else stop(msg, call. = FALSE, domain = NA)})
13: library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, warn.conflicts = warn.conflicts, quietly = quietly)
14: doTryCatch(return(expr), name, parentenv, handler)
15: tryCatchOne(expr, names, parentenv, handlers[[1L]])
16: tryCatchList(expr, classes, parentenv, handlers)
17: tryCatch(library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, warn.conflicts = warn.conflicts, quietly = quietly), error = function(e) e)
18: require(ggplot2)
An irrecoverable exception occurred. R is aborting now ...

**Comment by mikessh** [comment]
I assume the problem was resolved. For the other issue see https://github.com/mikessh/vdjtools/issues/71

**Comment by mimisikai** [comment]
Issue is still there, not been solved out. 

 

R version 3.4.0. All packages that vdjtool requires have been installed.
Also try the R in console and load ggplot2 library, R can be accessed, and ggplot2 load successfully.
Reinstall the R and all packages, the error still show up.

**Comment by mikessh** [comment]
I mean the original issue you have created (parsing MIXCR)
